--- # Notification and dandling events
- hosts: vms
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: ssh
  connection: ssh

  tasks:
  - name: install nginx web server
    yum:
      name: nginx
      state: latest
    notify:
    - enable and start the nginx service

  handlers:
  - name: enable and start the nginx service
    service:
      name: nginx
      enabled: yes
      state: restarted
