--- # This is a sctructural YAML example to install HTTPD on CentOS 7
- hosts: vms
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes

  vars:
    username: myuser

  tasks:
  - name: Install HTTPD server on CentOS 7 nodes
    yum:
      name: httpd
      state: latest
    notify:
    - startserservice

  - name: Install nginx server on CentOS 7 nodes
    yum:
      name: nginx
      state: latest
    notify:
    - startservice

  handlers:
  - name: startservice
    service:
      name: httpd
      state: stopped
